apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeps-api
  namespace: meeps-dev
  labels:
    app.kubernetes.io/name: meeps-api
    app.kubernetes.io/instance: meeps-dev
    app.kubernetes.io/part-of: kubernetes-production-foundations
automountServiceAccountToken: false
